name: run-tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-latest]
                php: ['8.4', '8.3', '8.2', '8.1', '8.0', '7.4']
                laravel: ['12.*', '11.*', '10.*', '9.*', '8.*', '7.*']
                dependency-version: [prefer-stable]
                include:
                    -   laravel: 12.*
                        testbench: 10.*
                        phpunit: ^11.0
                    -   laravel: 11.*
                        testbench: 9.*
                        phpunit: ^11.0
                    -   laravel: 10.*
                        testbench: 8.*
                        phpunit: ^10.0
                    -   laravel: 9.*
                        testbench: 7.*
                        phpunit: ^9.3
                    -   laravel: 8.*
                        testbench: 6.*
                        phpunit: ^9.3
                    -   laravel: 7.*
                        testbench: 5.*
                        phpunit: ^9.3
                exclude:
                    -   laravel: 12.*
                        php: 8.1
                    -   laravel: 12.*
                        php: 8.0
                    -   laravel: 12.*
                        php: 7.4
                    -   laravel: 11.*
                        php: 8.1
                    -   laravel: 11.*
                        php: 8.0
                    -   laravel: 11.*
                        php: 7.4
                    -   laravel: 10.*
                        php: 8.0
                    -   laravel: 10.*
                        php: 7.4
                    -   laravel: 9.*
                        php: 8.4
                    -   laravel: 9.*
                        php: 8.3
                    -   laravel: 9.*
                        php: 7.4
                    -   laravel: 8.*
                        php: 8.4
                    -   laravel: 8.*
                        php: 8.3
                    -   laravel: 8.*
                        php: 8.2
                    -   laravel: 7.*
                        php: 8.4
                    -   laravel: 7.*
                        php: 8.3
                    -   laravel: 7.*
                        php: 8.2
                    -   laravel: 7.*
                        php: 8.1

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v7

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
                    coverage: none

            -   name: Install dependencies
                run: |
                    if [ "${{ matrix.php }}" = "7.4" ] || [ "${{ matrix.php }}" = "8.0" ] || [ "${{ matrix.php }}" = "8.1" ]; then
                        composer remove --dev laravel/pint phpstan/phpstan --no-update --no-interaction
                    fi
                    composer config audit.block-insecure false
                    composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "phpunit/phpunit:${{ matrix.phpunit }}" --no-interaction --no-update --dev
                    composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-audit

            -   name: Execute tests
                run: vendor/bin/phpunit
